services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app
    command: npm start

  test:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    command: npm test
