name: React CI with Docker

on: [ push, pull_request ]

jobs:
  docker-build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up Docker Compose
        run: |
          docker --version
          docker compose --version

      - name: Build and Start Containers
        run: |
          docker compose up --build -d

      - name: Check running containers
        run: docker ps

      - name: Shutdown Docker Compose
        if: always()
        run: docker compose down